trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- bash: az group create --name maumau --location brazilsouth
  displayName: 'Show Azure CLI version'
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)