trigger:
- main

pool:
  vmImage: ubuntu-latest

steps: 
- bash: az login
  displayName: "Connet into the Azure Portal"

- bash: az group create --name miris --location brazilsouth
  displayName: "Show Azure CLI version"
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)